http:
  port: "8081"
  
sfdc:
  usrname: "sahitya@tcs.com"
  pwd: "TiMU@pwd5"
  token: "CXogkSXrv2TTkl74pqfWZ1PS" 
  
file:
  accountsDir: "D:/APDevFundamentals4.3_studentFiles_SP_30oct2020/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"